manycats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
end

manycats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

manycats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  require 'action_view'
  require 'action_view/helpers'
  include ActionView::Helpers::DateHelper

  COLORS = %w(black white grey red blue green)
  SEX = %w(M F)
  validates :birth_date, :name, :sex, :description, :color, presence: true
  validates :color, inclusion: { in: COLORS, message: "has to be black, white, grey,red, blue, or green" }
  validates :sex, inclusion: { in: SEX, message: "has to be M or F" }
  validate :valid_birth_date

  has_many :rental_requests,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    now = Date.today
    year = now.year - birth_date.year
  end

  def valid_birth_date
    errors[:birth_date] << "is not valid" if birth_date.nil? || birth_date.year > 2019
  end
end

manycats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord

  STATUS = %w(PENDING DENIED APPROVED)
  validates :cat_id, :start_date, :end_date, :status
  validates :status, inclusion: { in: STATUS, message: "not valid" }

  belongs_to :cat,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    CatRentalRequest
  end
end

manycats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

manycats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      @cat = Cat.find_by(id: params[:id])
      render :edit
    end
  end

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end
end

manycats/app/helpers/application_helper.rb
module ApplicationHelper
end

manycats/app/views/cats/_form.html.erb
<% if cat.persisted? %>
    <% action_url = cat_url(cat) %>
    <% button = "Edit this cat" %>
<% else %>
    <% action_url = cats_url %>
    <% button = "Create this cat" %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value = "patch">
  <% end %>

  <label>Name:
    <input type="text" name="cat[name]" value="<%= cat.name %>">
  </label>

  <br>
  <br>

  <label>Birth Date:
    <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  </label>

  <br>
  <br>

  <label>Color:
    <select name="cat[color]">
      <% Cat::COLORS.each do |color|%>
      <option value="<%= color %>" <%= color == cat.color ? "selected" : "" %>><%= color.capitalize%></option>
      <% end %>
    </select>
  </label>

  <br>
  <br>

  <label>Sex:
    <input type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %>>M
    <input type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>>F
  </label>

  <br>
  <br>

  <label>Description:
    <textarea name="cat[description]">
      <%= cat.description %>
    </textarea>
  </label>

  <br>
  <br>

  <input type="submit" value="<%= button %>">
</form>

manycats/app/views/cats/edit.html.erb
<h1>Edit a cat</h1>

<%= render 'form', cat: @cat, action: :edit %>

manycats/app/views/cats/index.html.erb
<h1>All the cats</h1>

<% @cats.each do |cat|%>
  <ul>
    <li><%= cat.name %></li>
    <a href="<%= cat_url(cat) %>">Adopt me, human</a>
  </ul>
<% end %>

manycats/app/views/cats/new.html.erb
<h1>Create a new cat</h1>

<%= render 'form', cat: @cat, action: :new %>

manycats/app/views/cats/show.html.erb
<style>
table, th, td {
  border: 1px solid black;
  text-align: left;
}
</style>
<h1><%= @cat.name %></h1>

<p><%= @cat.description %></p>

<table style="width:100%">
  <tr>
    <th>Birth Date</th>
    <th>Color</th>
    <th>Sex</th>
  </tr>

  <tr>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
  </tr>
</table>

manycats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manycats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>